### ISSUE TITLE
Exception on a simple start...

### ISSUE THREAD

**Issue by EmanueleRossi** [youribonnaffe/gradle-format-plugin#20]
I'm trying to format my project, using the ".properties" file, but i get an exception I can't avoid:

       Caused by: org.gradle.api.GradleException: FAILED format {C:\dev\src\WBCP\src\main\java\it\gpi\wbcp\entity\model\entity\ejb\UserEjb.java=java.lang.NullPointerException, C:\dev\src\WBCP\src\main\java\it\gpi\wbcp\entity\model\entity\ejb\RootEjb.java=java.lang.NullPointerException, C:\dev\src\WBCP\src\main\java\eclipseCodeStyle.java=java.lang.NullPointerException}
    	at com.github.youribonnaffe.gradle.format.FormatTask.format(FormatTask.groovy:85)
    	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

[eclipseCodeStyles.properties.txt](https://github.com/youribonnaffe/gradle-format-plugin/files/39339/eclipseCodeStyles.properties.txt)

**Comment by youribonnaffe** [comment]
Hi,
I could not reproduce the issue with your configuration file.
Could you please attach one of the formatted file (UserEjb for instance, make to sure to remove confidential data if any) so I can try to reproduce it on my side?

**Comment by EmanueleRossi** [comment]
Thank you! 

| Da: "Youri Bonnaffé" <notifications@github.com>
| A: "youribonnaffe/gradle-format-plugin"
| <gradle-format-plugin@noreply.github.com>
| Cc: "Emanuele Rossi" <emanuele.rossi@gpi.it>
| Inviato: Giovedì, 19 novembre 2015 22:57:22
| Oggetto: {Disarmed} Re: [gradle-format-plugin] Exception on a simple start...
| (#20)

| Hi,
| I could not reproduce the issue with your configuration file.
| Could you please attach one of the formatted file (UserEjb for instance, make to
| sure to remove confidential data if any) so I can try to reproduce it on my
| side?

| —
| Reply to this email directly or view it on GitHub .
