### ISSUE TITLE
task 'format' failed

### ISSUE THREAD

**Issue by obecker** [youribonnaffe/gradle-format-plugin#23]
I have just added the plugin to an existing project and invoked a first run.
It formatted a lot of files, so the plugin in general is working.

However, the output contains about 20 lines like this

    ====> could not format /path/to/my/project/package/foo/MyClass.java

and after that

    :my-submodule:format FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':my-submodule:format'.
    > FAILED importOrder format {/path/to/my/project/package/foo/DifferentClass.java=java.lang.NullPointerException, etc}

The curly braces actually contain a lot of other classes, all of them with =java.lang.NullPointerException. 
Using --stacktrace or --debug didn't really help. Any idea what's going wrong?

**Comment by youribonnaffe** [comment]
Would you be able to provide a small project that reproduces the error, maybe by just taking the build.gradle file and a few source files?

**Comment by obecker** [comment]
I have debugged it myself and was able to produce this stacktrace:

    java.lang.NullPointerException
	at java.util.Arrays.binarySearch(Arrays.java:1864)
	at org.eclipse.jdt.internal.formatter.Scribe.getCurrentCommentIndentation(Scribe.java:923)
	at org.eclipse.jdt.internal.formatter.Scribe.printBlockComment(Scribe.java:1656)
	at org.eclipse.jdt.internal.formatter.Scribe.printComment(Scribe.java:2690)
	at org.eclipse.jdt.internal.formatter.Scribe.printComment(Scribe.java:2412)
	at org.eclipse.jdt.internal.formatter.CodeFormatterVisitor.format(CodeFormatterVisitor.java:1004)
	at org.eclipse.jdt.internal.formatter.CodeFormatterVisitor.visit(CodeFormatterVisitor.java:5805)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
	at org.eclipse.jdt.internal.formatter.CodeFormatterVisitor.visit(CodeFormatterVisitor.java:3448)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:712)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:706)
	at org.eclipse.jdt.internal.formatter.CodeFormatterVisitor.format(CodeFormatterVisitor.java:904)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.formatCompilationUnit(DefaultCodeFormatter.java:244)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:166)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:149)
	at com.github.youribonnaffe.gradle.format.JavaFormatter.formatFile(JavaFormatter.java:41)
	at com.github.youribonnaffe.gradle.format.JavaFormatter$formatFile.call(Unknown Source)
	at com.github.youribonnaffe.gradle.format.FormatTask$1.format(FormatTask.groovy:50)
	at com.github.youribonnaffe.gradle.format.FormatTask$1.call(FormatTask.groovy:66)
	at com.github.youribonnaffe.gradle.format.FormatTask$1.call(FormatTask.groovy)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

The corresponding code in the `Scribe` class is

	private int getCurrentCommentIndentation(int start) {
		int linePtr = -Arrays.binarySearch(this.lineEnds, start);
		....

so `this.lineEnds` is apparently `null` (which seems to be allowed if I Iook at other occurrences of this field).

However, since this `Scribe`class is not yours I checked for a newer version and I found one.
After replacing the dependency `org.eclipse.tycho:org.eclipse.jdt.core:3.10.0.v20140604-1726` with the lastest version `3.11.1.v20150902-1521` the exception was gone.

Could you please update this dependency as well and release a new version of the plugin? 
Thanks a lot! Oliver

**Comment by youribonnaffe** [comment]
Thanks for the debugging Oliver!

It looks you did almost the everything so you want to submit a pull request
it will be more than welcome.
Truth be told I'm not using the plugin myself anymore so it might take me a
while to find a bit of time to work on it...

**Comment by obecker** [comment]
Ok, I can do that. Btw, I searched for a way to get access to the stacktraces without having to build and debug the plugin myself, see https://discuss.gradle.org/t/how-to-access-stacktrace-or-full-stacktrace-option-in-custom-plugin/14653
I look if I can add something near it as well.

**Comment by obecker** [comment]
Finally, here it is: https://github.com/youribonnaffe/gradle-format-plugin/pull/24

**Comment by youribonnaffe** [comment]
Thanks for the PR @obecker !
I published a 1.5 version with your fix.

**Comment by obecker** [comment]
Oh oh, it seems I have added another, even worse issue.
After upgrading the dependency the error is gone, however, the plugin also doesn't format any more (though organizing imports still works).
Shame on me, I have completely ignored the plugin tests, as they would have shown me this problem.
I will try to locate the cause of the problem and see what we can do about this.

**Comment by youribonnaffe** [comment]
Mmm strane i did the tests before merging and it was ok

**Comment by obecker** [comment]
Ok, I see. Actually (and strangely) the plugin tests itself do work. 
However, running the 1.5 version of the plugin against my project at work produces a
`java.lang.NoClassDefFoundError: org/eclipse/core/resources/IResource`
(which wasn't reported so I thought I had fixed the plugin).
After adding the missing dependency to the plugin I see other exceptions during the plugin execution:

    java.lang.IndexOutOfBoundsException: Index: 204, Size: 204
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.eclipse.jdt.internal.formatter.TokenManager.get(TokenManager.java:68)
        ...

I wonder, why are you using the `org.eclipse.tycho` versions of the dependency at all? Apparently project tycho is still in the incubation phase and not finished.

**Comment by obecker** [comment]
One more observation: I wondered whether this `IndexOutOfBoundsException` has something to do with the parallel execution of your plugin. And indeed, after removing it from the plugin this exception was also gone. Unfortunately the plugin formatted one Java file in a way that it couldn't be compiled any more. :(

**Comment by youribonnaffe** [comment]
The Eclipse dependencies were a pain the *ss, so I guess I took the one I found and that seemed to work. Unfortunately they are not officially published on Maven central.

**Comment by obecker** [comment]
Youri, you wrote above "Truth be told I'm not using the plugin myself anymore so it might take me a
while to find a bit of time to work on it..."
I just found this project: https://github.com/diffplug/spotless
It is based on your work and it seems to be actively maintained. Moreover, it worked on my project on the first try (except for the same compile error in the formatted code, but that's apparently Eclipse's fault and something I can work around).
I don't want to bother you, but if you don't plan to continue the work on your plugin it is perhaps a good idea to link your project to the spotless project. This will save you from new issues popping up and your users from frustration when trying your plugin.
Thanks a lot for starting this work.

**Comment by youribonnaffe** [comment]
Good thinking, I just edited the Readme to reflect that and linked to the Spotless plugin.
